/* File Sharing Studio: static QR generator + private local Wi-Fi transfer. */
(function(){'use strict';
const ID='tabFileSharing', ACCENT='#0F766E', ACCENT2='#14B8A6';
const QR_LIB='https://cdn.jsdelivr.net/npm/qr-code-styling@1.9.2/lib/qr-code-styling.min.js';
let qr=null, qrLibPromise=null, logoData='', transferFiles=[], transferToken='', transferTimer=null, transferMode='send';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>{n=Number(n)||0;const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<4){n/=1024;i++;}return (n<10&&i?n.toFixed(1):Math.round(n))+' '+u[i]};
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('QR styling library could not be loaded.'));document.head.appendChild(s);});}
async function ensureQr(){if(window.QRCodeStyling)return window.QRCodeStyling;if(!qrLibPromise)qrLibPromise=loadScript(QR_LIB);await qrLibPromise;return window.QRCodeStyling;}
function localBase(){return window.OMNI_LOCAL_ENGINE_URL||'http://127.0.0.1:8765'}
async function localToken(){if(window.OMNI_TOKEN)return window.OMNI_TOKEN;const r=await fetch(localBase()+'/api/health',{cache:'no-store'});const j=await r.json();if(!r.ok||!j.token)throw new Error('Start Omni Local Engine on your Mac first.');window.OMNI_TOKEN=j.token;return j.token;}
async function localFetch(path,opts={}){const t=await localToken(),h=new Headers(opts.headers||{});h.set('X-Omni-Token',t);const r=await fetch(localBase()+path,{...opts,headers:h});const j=r.headers.get('content-type')?.includes('application/json')?await r.json():null;if(!r.ok)throw new Error(j?.error||'Local Engine request failed.');return j;}
const val=id=>document.getElementById(id)?.value||'';
function qrData(){const t=val('fsQrType');if(t==='wifi')return 'WIFI:T:'+val('fsWifiSecurity')+';S:'+val('fsWifiSsid').replace(/[;,:]/g,'\\$&')+';P:'+val('fsWifiPass').replace(/[;,:]/g,'\\$&')+';H:false;;';if(t==='contact')return ['BEGIN:VCARD','VERSION:3.0','FN:'+val('fsContactName'),'TEL:'+val('fsContactPhone'),'EMAIL:'+val('fsContactEmail'),'URL:'+val('fsContactUrl'),'END:VCARD'].join('\n');if(t==='email')return 'mailto:'+val('fsEmailTo')+'?subject='+encodeURIComponent(val('fsEmailSubject'))+'&body='+encodeURIComponent(val('fsEmailBody'));if(t==='phone')return 'tel:'+val('fsPhone');if(t==='sms')return 'SMSTO:'+val('fsSmsPhone')+':'+val('fsSmsText');if(t==='location')return 'geo:'+val('fsLat')+','+val('fsLon');return val('fsQrText').trim();}
function qrOpts(data){const fg=val('fsQrFg')||'#172B4D',bg=val('fsQrBg')||'#FFFFFF',o={width:360,height:360,type:'svg',data,margin:18,qrOptions:{errorCorrectionLevel:val('fsQrEcc')||'H'},dotsOptions:{type:val('fsQrDots')||'rounded',color:fg},cornersSquareOptions:{type:val('fsQrCorner')||'extra-rounded',color:fg},cornersDotOptions:{type:val('fsQrCornerDot')||'dot',color:fg},backgroundOptions:{color:document.getElementById('fsQrTransparent')?.checked?'transparent':bg},imageOptions:{hideBackgroundDots:true,imageSize:.32,margin:8,saveAsBlob:true}};if(document.getElementById('fsQrGradient')?.checked)o.dotsOptions.gradient={type:'linear',rotation:.78,colorStops:[{offset:0,color:fg},{offset:1,color:val('fsQrFg2')||'#D9571F'}]};if(logoData)o.image=logoData;return o;}
async function renderQr(){const data=qrData(),m=document.getElementById('fsQrPreview');if(!m)return;if(!data){m.innerHTML='<div class="fs-empty">Enter something to encode.</div>';return}try{const C=await ensureQr();if(!qr){qr=new C(qrOpts(data));qr.append(m)}else qr.update(qrOpts(data));document.getElementById('fsQrDataPreview').textContent=data.length>180?data.slice(0,180)+'…':data;document.getElementById('fsQrStatus').textContent='Static QR • no Omni server • no expiry'}catch(e){m.innerHTML='<div class="fs-empty">'+esc(e.message)+'</div>';}}
function showQrFields(){const t=val('fsQrType');document.querySelectorAll('[data-fs-q]').forEach(x=>x.style.display=x.dataset.fsQ===t?'grid':'none');document.getElementById('fsQrGeneric').style.display=['wifi','contact','email','phone','sms','location'].includes(t)?'none':'grid';renderQr()}
async function downloadQr(ext){if(!qr)await renderQr();if(qr)await qr.download({name:'omni-static-qr',extension:ext})}
function panel(){const p=document.createElement('div');p.className='module-panel';p.id=ID;p.innerHTML=[
'<section class="studio-workspace-head fs-head"><div class="studio-workspace-copy"><div class="studio-workspace-kicker"><i class="studio-workspace-dot"></i> FILE SHARING</div><h2 class="studio-workspace-title">File Sharing Studio</h2><p class="studio-workspace-desc">Create permanent static QR codes or move files directly between your Mac and another device over the same local Wi-Fi network.</p></div><div class="studio-workspace-meta"><span class="studio-meta-chip primary">QR + LAN</span><span class="studio-meta-chip">NO CLOUD</span><span class="studio-meta-chip">MAC READY</span></div></section>',
'<div class="fs-modebar"><button type="button" class="fs-mode active" data-mode="qr">▦ QR Generator</button><button type="button" class="fs-mode" data-mode="transfer">⇄ Nearby Transfer</button></div>',
'<div class="fs-panel fs-qr-panel"><div class="fs-grid"><div class="card fs-card"><div class="code-kicker">STATIC QR</div><h2>Generate a QR that stays yours</h2><div class="sub">The destination is encoded directly into the QR. Omni does not create a redirect or tracking link.</div><div class="form-group"><label>Content type</label><select id="fsQrType" class="form-select"><option value="url">Website / Link</option><option value="text">Plain Text</option><option value="wifi">Wi-Fi Network</option><option value="contact">Contact / vCard</option><option value="email">Email</option><option value="phone">Phone</option><option value="sms">SMS</option><option value="location">Location</option></select></div><div id="fsQrGeneric" class="form-group"><label>Content</label><textarea id="fsQrText" class="form-textarea" rows="4" placeholder="https://example.com"></textarea></div>',
'<div class="fs-special" data-fs-q="wifi"><label>Network name<input id="fsWifiSsid" class="form-input"></label><label>Security<select id="fsWifiSecurity" class="form-select"><option value="WPA">WPA / WPA2 / WPA3</option><option value="WEP">WEP</option><option value="nopass">No password</option></select></label><label>Password<input id="fsWifiPass" class="form-input" type="password"></label></div><div class="fs-special" data-fs-q="contact"><label>Name<input id="fsContactName" class="form-input"></label><label>Phone<input id="fsContactPhone" class="form-input"></label><label>Email<input id="fsContactEmail" class="form-input"></label><label>Website<input id="fsContactUrl" class="form-input" placeholder="https://"></label></div><div class="fs-special" data-fs-q="email"><label>To<input id="fsEmailTo" class="form-input"></label><label>Subject<input id="fsEmailSubject" class="form-input"></label><label>Body<textarea id="fsEmailBody" class="form-textarea" rows="3"></textarea></label></div><div class="fs-special" data-fs-q="phone"><label>Phone<input id="fsPhone" class="form-input" placeholder="+91..."></label></div><div class="fs-special" data-fs-q="sms"><label>Phone<input id="fsSmsPhone" class="form-input"></label><label>Message<textarea id="fsSmsText" class="form-textarea" rows="3"></textarea></label></div><div class="fs-special fs-special-2" data-fs-q="location"><label>Latitude<input id="fsLat" class="form-input"></label><label>Longitude<input id="fsLon" class="form-input"></label></div></div></div>',
'<div class="card fs-card"><div class="code-kicker">DESIGN</div><h2>Shape it</h2><div class="fs-design-grid"><label>Dots<select id="fsQrDots" class="form-select"><option value="square">Square</option><option value="rounded" selected>Rounded</option><option value="dots">Dots</option><option value="classy">Classy</option><option value="classy-rounded">Classy rounded</option><option value="extra-rounded">Extra rounded</option></select></label><label>Corner style<select id="fsQrCorner" class="form-select"><option value="square">Square</option><option value="rounded">Rounded</option><option value="dot">Dot</option><option value="extra-rounded" selected>Extra rounded</option></select></label><label>Corner dot<select id="fsQrCornerDot" class="form-select"><option value="square">Square</option><option value="dot" selected>Dot</option><option value="rounded">Rounded</option></select></label><label>Error correction<select id="fsQrEcc" class="form-select"><option>L</option><option>M</option><option>Q</option><option selected>H</option></select></label><label>Foreground<input id="fsQrFg" class="form-input" type="color" value="#172B4D"></label><label>Accent<input id="fsQrFg2" class="form-input" type="color" value="#D9571F"></label><label>Background<input id="fsQrBg" class="form-input" type="color" value="#FFFFFF"></label><label class="fs-check"><input id="fsQrGradient" type="checkbox"> Gradient dots</label><label class="fs-check"><input id="fsQrTransparent" type="checkbox"> Transparent background</label></div><label class="fs-logo">Optional center logo <input id="fsQrLogo" type="file" accept="image/*"></label><div class="fs-actions"><button id="fsQrPng" class="btn btn-primary" type="button">Download PNG</button><button id="fsQrSvg" class="btn btn-secondary" type="button">Download SVG</button></div></div></div><div class="card fs-qr-result"><div><div class="code-kicker">PREVIEW</div><h2>Static QR</h2><p id="fsQrStatus" class="fs-status">Enter content to generate.</p><code id="fsQrDataPreview"></code></div><div id="fsQrPreview" class="fs-qr-preview"><div class="fs-empty">Your QR will appear here.</div></div></div></div>',
'<div class="fs-panel fs-transfer-panel" style="display:none"><div class="fs-transfer-hero card"><div><div class="code-kicker">PRIVATE LAN TRANSFER</div><h2>Mac ↔ Phone, without cloud</h2><p class="sub">Start a temporary transfer server on your Mac. Your phone scans the QR, then downloads or uploads through your local Wi-Fi network.</p><div class="fs-lan-note">● Same Wi-Fi required · files stay on the local network · session expires automatically</div></div><div class="fs-transfer-mode"><label>Transfer direction<select id="fsTransferMode" class="form-select"><option value="send">Send files from Mac</option><option value="receive">Receive files on Mac</option></select></label><div class="fs-drop" id="fsDrop"><input id="fsFiles" type="file" multiple hidden><strong>Drop files here</strong><span>or choose files</span><button id="fsPick" class="btn btn-secondary" type="button">Select Files</button></div><div id="fsFileList" class="fs-file-list"></div><div class="fs-transfer-actions"><button id="fsStart" class="btn btn-primary" type="button">Start Local Transfer</button><button id="fsStop" class="btn btn-secondary" type="button" disabled>Stop</button></div></div></div><div class="fs-transfer-grid"><div class="card fs-session"><div class="code-kicker">PAIR DEVICE</div><h2>Scan this QR</h2><div id="fsTransferQr" class="fs-transfer-qr"><div class="fs-empty">Start a transfer to create the temporary QR.</div></div><div id="fsTransferPin" class="fs-pin"></div><div id="fsTransferUrl" class="fs-transfer-url"></div><button id="fsCopyUrl" class="btn btn-secondary" type="button" disabled>Copy transfer link</button></div><div class="card fs-session"><div class="code-kicker">SESSION</div><h2 id="fsTransferState">Ready</h2><div id="fsTransferStatus" class="fs-status">Nothing is shared yet.</div><div id="fsTransferFiles" class="fs-received-list"></div><div class="fs-security-list"><span>✓ Random session token</span><span>✓ Temporary session</span><span>✓ Automatic cleanup</span><span>✓ LAN server stops when session ends</span></div></div></div></div>'
].join('');return p}
function install(){if(document.getElementById(ID))return;const nav=document.querySelector('.nav-bar'),container=document.querySelector('.container');if(!nav||!container)return;const b=document.createElement('button');b.type='button';b.className='nav-btn';b.dataset.tab=ID;b.innerHTML='<span class="studio-icon"><span class="studio-svg">⇄</span></span><span class="studio-label">File Sharing</span><small>QR • LAN</small>';nav.appendChild(b);const p=panel();container.appendChild(p);bind(b,p)}
function activate(on,b,p){if(on){document.querySelectorAll('.module-panel').forEach(x=>x.classList.toggle('active',x===p));document.querySelectorAll('.nav-bar .nav-btn').forEach(x=>x.classList.toggle('active',x===b));document.body.classList.add('studio-mode');document.body.dataset.activeStudio=ID;document.body.style.setProperty('--active-studio-accent',ACCENT);document.body.style.setProperty('--active-studio-accent-2',ACCENT2);document.body.style.setProperty('--active-studio-soft','rgba(15,118,110,.14)')}else{b.classList.remove('active');p.classList.remove('active')}}
function bind(b,p){b.onclick=e=>{e.preventDefault();e.stopPropagation();activate(true,b,p);p.scrollIntoView({behavior:'smooth',block:'start'})};document.addEventListener('click',e=>{const n=e.target.closest?.('.nav-bar .nav-btn');if(n&&n!==b)activate(false,b,p)});p.querySelectorAll('.fs-mode').forEach(x=>x.onclick=()=>{p.querySelectorAll('.fs-mode').forEach(y=>y.classList.toggle('active',y===x));p.querySelector('.fs-qr-panel').style.display=x.dataset.mode==='qr'?'block':'none';p.querySelector('.fs-transfer-panel').style.display=x.dataset.mode==='transfer'?'block':'none'});
p.querySelector('#fsQrType').onchange=showQrFields;p.querySelectorAll('input,select,textarea').forEach(x=>x.addEventListener('input',()=>{if(x.id!=='fsQrLogo')renderQr()}));p.querySelector('#fsQrLogo').onchange=async e=>{const f=e.target.files?.[0];if(f){logoData=await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)});renderQr()}};p.querySelector('#fsQrPng').onclick=()=>downloadQr('png');p.querySelector('#fsQrSvg').onclick=()=>downloadQr('svg');
p.querySelector('#fsTransferMode').onchange=e=>{transferMode=e.target.value;p.querySelector('#fsFileList').innerHTML='';setTransferStatus(transferMode==='send'?'Select files to share from the Mac.':'Start an empty session and send files from your phone.','')};p.querySelector('#fsPick').onclick=()=>p.querySelector('#fsFiles').click();p.querySelector('#fsFiles').onchange=e=>addFiles(e.target.files);const d=p.querySelector('#fsDrop');['dragenter','dragover'].forEach(n=>d.addEventListener(n,e=>{e.preventDefault();d.classList.add('dragover')}));['dragleave','drop'].forEach(n=>d.addEventListener(n,e=>{e.preventDefault();d.classList.remove('dragover')}));d.ondrop=e=>addFiles(e.dataTransfer.files);p.querySelector('#fsStart').onclick=startTransfer;p.querySelector('#fsStop').onclick=()=>stopTransfer();p.querySelector('#fsCopyUrl').onclick=()=>navigator.clipboard?.writeText(val('fsTransferUrl'));showQrFields()}
function setTransferStatus(t,k){const e=document.getElementById('fsTransferStatus');if(e){e.textContent=t;e.className='fs-status '+(k||'')}}
function addFiles(fs){for(const f of fs){if(f.size>8*1024**3){setTransferStatus(f.name+' is too large for the local transfer limit.','warn');continue}transferFiles.push(f)}const e=document.getElementById('fsFileList');e.innerHTML=transferFiles.map((f,i)=>'<div><span>'+esc(f.name)+'</span><small>'+fmt(f.size)+'</small><button type="button" data-r="'+i+'">×</button></div>').join('');e.querySelectorAll('[data-r]').forEach(x=>x.onclick=()=>{transferFiles.splice(+x.dataset.r,1);addFiles([])})}
async function uploadSelected(){const ids=[];for(const f of transferFiles){setTransferStatus('Uploading '+f.name+' to the Mac transfer session…','working');const t=await localToken();const r=await fetch(localBase()+'/api/upload',{method:'POST',headers:{'X-Omni-Token':t,'X-Filename':encodeURIComponent(f.name),'Content-Type':f.type||'application/octet-stream'},body:f});const j=await r.json();if(!r.ok)throw new Error(j.error||'Upload failed');ids.push(j.file_id)}return ids}
async function startTransfer(){if(transferToken)await stopTransfer(false);transferMode=val('fsTransferMode');try{if(transferMode==='send'&&!transferFiles.length)throw new Error('Select at least one file to send from the Mac.');const ids=transferMode==='send'?await uploadSelected():[];const j=await localFetch('/api/transfer/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:transferMode,file_ids:ids,ttl:900})});transferToken=j.token;document.getElementById('fsStart').disabled=true;document.getElementById('fsStop').disabled=false;document.getElementById('fsTransferState').textContent='Waiting for device';document.getElementById('fsTransferPin').textContent='PIN '+j.pin;document.getElementById('fsTransferUrl').textContent=j.url;document.getElementById('fsCopyUrl').disabled=false;const m=document.getElementById('fsTransferQr');m.innerHTML='';const C=await ensureQr();new C({width:310,height:310,type:'svg',data:j.url,margin:14,dotsOptions:{type:'rounded',color:ACCENT},cornersSquareOptions:{type:'extra-rounded',color:ACCENT},cornersDotOptions:{type:'dot',color:ACCENT},backgroundOptions:{color:'#fff'}}).append(m);setTransferStatus('Local transfer is live. Scan the QR on your phone.','ok');pollTransfer()}catch(e){setTransferStatus(e.message,'warn')}}
async function pollTransfer(){if(!transferToken)return;try{const j=await localFetch('/api/transfer/status?token='+encodeURIComponent(transferToken));document.getElementById('fsTransferState').textContent=j.connected?'Device connected':'Waiting for device';const e=document.getElementById('fsTransferFiles');e.innerHTML=(j.files||[]).map(f=>'<div class="fs-received"><div><b>'+esc(f.name)+'</b><small>'+fmt(f.size)+'</small></div><a class="btn btn-secondary" href="'+localBase()+'/api/transfer/download/'+encodeURIComponent(transferToken)+'/'+encodeURIComponent(f.id)+'" download>Download</a></div>').join('')||'<div class="fs-empty-inline">No transferred files yet.</div>';if(j.connected)setTransferStatus(transferMode==='send'?'Device connected — download the shared files on your phone.':'Device connected — files can now be sent to this Mac.','ok')}catch(e){setTransferStatus(e.message,'warn')}transferTimer=setTimeout(pollTransfer,1800)}
async function stopTransfer(){if(transferTimer){clearTimeout(transferTimer);transferTimer=null}if(transferToken){try{await localFetch('/api/transfer/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:transferToken})})}catch(e){}}transferToken='';document.getElementById('fsStart').disabled=false;document.getElementById('fsStop').disabled=true;document.getElementById('fsCopyUrl').disabled=true;document.getElementById('fsTransferQr').innerHTML='<div class="fs-empty">Start a transfer to create the temporary QR.</div>';document.getElementById('fsTransferPin').textContent='';document.getElementById('fsTransferUrl').textContent='';document.getElementById('fsTransferState').textContent='Ready';document.getElementById('fsTransferFiles').innerHTML='';setTransferStatus('Transfer session stopped.','')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();window.addEventListener('beforeunload',()=>{if(transferToken)navigator.sendBeacon?.(localBase()+'/api/transfer/stop',new Blob([JSON.stringify({token:transferToken})],{type:'application/json'}))});
})();