/* File Sharing Studio: static QR generator + private local Wi-Fi transfer. */
(function(){'use strict';
const ID='tabFileSharing', ACCENT='#0F766E', ACCENT2='#14B8A6';
const QR_LIB='https://cdn.jsdelivr.net/npm/qr-code-styling@1.9.2/lib/qr-code-styling.min.js';
const QR_PLAIN='./qrcode_generator.js'; // bundled, works offline (MIT, Kazuhiko Arase)
let qr=null, qrLibPromise=null, plainQrPromise=null, logoData='', transferFiles=[], transferToken='', transferTimer=null, countdownTimer=null, transferMode='send', transferExpires=0, lastFileCount=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>{n=Number(n)||0;const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<4){n/=1024;i++;}return (n<10&&i?n.toFixed(1):Math.round(n))+' '+u[i]};
const extOf=n=>(/\.([a-z0-9]{1,5})$/i.exec(n||'')||[,'file'])[1];
const $=id=>document.getElementById(id);
function loadScript(src,msg){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error(msg||'Script could not be loaded.'));document.head.appendChild(s);});}
async function ensureQr(){if(window.QRCodeStyling)return window.QRCodeStyling;if(!qrLibPromise)qrLibPromise=loadScript(QR_LIB,'QR designer needs an internet connection the first time (styling library).').catch(e=>{qrLibPromise=null;throw e});await qrLibPromise;return window.QRCodeStyling;}
async function ensurePlainQr(){if(window.qrcode)return window.qrcode;if(!plainQrPromise)plainQrPromise=loadScript(QR_PLAIN,'Bundled QR encoder is missing.').catch(e=>{plainQrPromise=null;throw e});await plainQrPromise;return window.qrcode;}
/* Offline QR for the pairing link: crisp SVG, no network needed. */
async function plainQrSvg(text,color){const make=await ensurePlainQr();const q=make(0,'M');q.addData(text);q.make();const n=q.getModuleCount(),m=4;let d='';for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(q.isDark(r,c))d+='M'+(c+m)+' '+(r+m)+'h1v1h-1z';const s=n+m*2;return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+s+' '+s+'" shape-rendering="crispEdges" role="img" aria-label="Transfer QR code"><rect width="'+s+'" height="'+s+'" fill="#fff"/><path d="'+d+'" fill="'+color+'"/></svg>';}
function localBase(){return window.OMNI_LOCAL_ENGINE_URL||'http://127.0.0.1:8765'}
async function localToken(){if(window.OMNI_TOKEN)return window.OMNI_TOKEN;let r,j;try{r=await fetch(localBase()+'/api/health',{cache:'no-store'});j=await r.json()}catch(e){throw new Error('Omni Local Engine is not running. Start it on this computer, then try again.')}if(!r.ok||!j.token)throw new Error('Omni Local Engine is not running. Start it on this computer, then try again.');window.OMNI_TOKEN=j.token;return j.token;}
async function localFetch(path,opts={}){const t=await localToken(),h=new Headers(opts.headers||{});h.set('X-Omni-Token',t);const r=await fetch(localBase()+path,{...opts,headers:h});const j=r.headers.get('content-type')?.includes('application/json')?await r.json():null;if(!r.ok){const err=new Error(j?.error||'Local Engine request failed.');err.status=r.status;throw err}return j;}
const val=id=>$(id)?.value||'';

/* ---------- Static QR designer (unchanged behaviour) ---------- */
function qrData(){const t=val('fsQrType');if(t==='wifi')return 'WIFI:T:'+val('fsWifiSecurity')+';S:'+val('fsWifiSsid').replace(/[;,:]/g,'\\$&')+';P:'+val('fsWifiPass').replace(/[;,:]/g,'\\$&')+';H:false;;';if(t==='contact')return ['BEGIN:VCARD','VERSION:3.0','FN:'+val('fsContactName'),'TEL:'+val('fsContactPhone'),'EMAIL:'+val('fsContactEmail'),'URL:'+val('fsContactUrl'),'END:VCARD'].join('\n');if(t==='email')return 'mailto:'+val('fsEmailTo')+'?subject='+encodeURIComponent(val('fsEmailSubject'))+'&body='+encodeURIComponent(val('fsEmailBody'));if(t==='phone')return 'tel:'+val('fsPhone');if(t==='sms')return 'SMSTO:'+val('fsSmsPhone')+':'+val('fsSmsText');if(t==='location')return 'geo:'+val('fsLat')+','+val('fsLon');if(t==='url')return val('fsQrUrl').trim();return val('fsQrText').trim();}
function qrOpts(data){const fg=val('fsQrFg')||'#172B4D',bg=val('fsQrBg')||'#FFFFFF',o={width:360,height:360,type:'svg',data,margin:18,qrOptions:{errorCorrectionLevel:val('fsQrEcc')||'H'},dotsOptions:{type:val('fsQrDots')||'rounded',color:fg},cornersSquareOptions:{type:val('fsQrCorner')||'extra-rounded',color:fg},cornersDotOptions:{type:val('fsQrCornerDot')||'dot',color:fg},backgroundOptions:{color:$('fsQrTransparent')?.checked?'transparent':bg},imageOptions:{hideBackgroundDots:true,imageSize:.32,margin:8,saveAsBlob:true}};if($('fsQrGradient')?.checked)o.dotsOptions.gradient={type:'linear',rotation:.78,colorStops:[{offset:0,color:fg},{offset:1,color:val('fsQrFg2')||'#D9571F'}]};if(logoData)o.image=logoData;return o;}
async function renderQr(){const data=qrData(),m=$('fsQrPreview');if(!m)return;const status=$('fsQrStatus'),dp=$('fsQrDataPreview');if(!data){if(qr){qr=null}m.innerHTML='<div class="fs-empty"><b>▦</b>Your QR will appear here.</div>';dp.textContent='';status.textContent='Enter content to generate.';status.className='fs-status';return}try{const C=await ensureQr();if(!qr||!m.querySelector('svg,canvas')||m.dataset.plain){delete m.dataset.plain;m.innerHTML='';qr=new C(qrOpts(data));qr.append(m)}else qr.update(qrOpts(data));dp.textContent=data.length>180?data.slice(0,180)+'…':data;status.textContent='Static QR · no Omni server · never expires';status.className='fs-status ok'}catch(e){qr=null;try{m.innerHTML=await plainQrSvg(data,val('fsQrFg')||'#172B4D');m.dataset.plain='1';dp.textContent=data.length>180?data.slice(0,180)+'…':data;status.textContent='Offline: plain QR (dot styles and logo need internet once). Still a permanent static QR.';status.className='fs-status ok'}catch(e2){m.innerHTML='<div class="fs-empty">'+esc(e.message)+'</div>';status.textContent=e.message;status.className='fs-status warn'}}}
function showQrFields(){const t=val('fsQrType');document.querySelectorAll('#'+ID+' [data-fs-q]').forEach(x=>{const on=x.dataset.fsQ===t;x.hidden=!on;x.style.display=on?'grid':'none'});const generic=$('fsQrGeneric'),url=$('fsQrUrl'),text=$('fsQrText'),label=$('fsQrContentLabel');const genericOn=t==='url'||t==='text';generic.hidden=!genericOn;generic.style.display=genericOn?'grid':'none';if(label)label.textContent=t==='text'?'Text':'Website / Link';if(url){url.hidden=t!=='url';url.style.display=t==='url'?'block':'none'}if(text){text.hidden=t!=='text';text.style.display=t==='text'?'block':'none'}renderQr()}
function saveBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
async function downloadQr(ext){if(!qr)await renderQr();if(qr){await qr.download({name:'omni-static-qr',extension:ext});return}const svg=$('fsQrPreview')?.querySelector('svg');if(!svg)return;const src=new XMLSerializer().serializeToString(svg);if(ext==='svg'){saveBlob(new Blob([src],{type:'image/svg+xml'}),'omni-static-qr.svg');return}const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=c.height=1024;const g=c.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(img,0,0,1024,1024);c.toBlob(b=>b&&saveBlob(b,'omni-static-qr.png'),'image/png')};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(src)}

/* ---------- Markup ---------- */
function panel(){const p=document.createElement('div');p.className='module-panel';p.id=ID;p.innerHTML=[
'<section class="studio-workspace-head fs-head"><div class="studio-workspace-copy"><div class="studio-workspace-kicker"><i class="studio-workspace-dot"></i> FILE SHARING</div><h2 class="studio-workspace-title">File Sharing Studio</h2><p class="studio-workspace-desc">Create permanent static QR codes or move files directly between this computer and your phone over the same Wi-Fi network.</p></div><div class="studio-workspace-meta"><span class="studio-meta-chip primary">QR + LAN</span><span class="studio-meta-chip">NO CLOUD</span><span class="studio-meta-chip">MAC READY</span></div></section>',
/* One mode switch (the two cards), instead of cards + a duplicate tab bar */
'<div class="fs-share-options" role="tablist" aria-label="File Sharing tools">',
 '<button type="button" class="fs-share-option fs-share-option-qr selected" role="tab" aria-selected="true" data-open-mode="qr"><span class="fs-share-option-icon">▦</span><span class="fs-share-option-text"><strong>QR Generator</strong><span>Permanent static QR for a link, Wi-Fi, contact, text and more.</span></span><span class="fs-share-check" aria-hidden="true">✓</span></button>',
 '<button type="button" class="fs-share-option fs-share-option-transfer" role="tab" aria-selected="false" data-open-mode="transfer"><span class="fs-share-option-icon">⇄</span><span class="fs-share-option-text"><strong>File Transfer</strong><span>Send files to your phone, or receive files from it, over the same Wi-Fi.</span></span><span class="fs-share-check" aria-hidden="true">✓</span></button>',
'</div>',
/* QR panel: fs-grid holds both cards; preview stays inside the QR panel */
'<div class="fs-panel fs-qr-panel"><div class="fs-grid">',
 '<div class="card fs-card"><div class="code-kicker">STATIC QR</div><h2>Generate a QR that stays yours</h2><div class="sub">The destination is encoded directly into the QR. Omni does not create a redirect or tracking link.</div>',
  '<div class="form-group"><label for="fsQrType">Content type</label><select id="fsQrType" class="form-select"><option value="url">Website / Link</option><option value="text">Plain Text</option><option value="wifi">Wi-Fi Network</option><option value="contact">Contact / vCard</option><option value="email">Email</option><option value="phone">Phone</option><option value="sms">SMS</option><option value="location">Location</option></select></div>',
  '<div id="fsQrGeneric" class="form-group fs-generic"><label id="fsQrContentLabel">Website / Link</label><input id="fsQrUrl" class="form-input" type="url" placeholder="https://example.com"><textarea id="fsQrText" class="form-textarea" rows="4" placeholder="Enter text to encode" style="display:none" hidden></textarea></div>',
  '<div class="fs-special" data-fs-q="wifi"><label>Network name<input id="fsWifiSsid" class="form-input"></label><label>Security<select id="fsWifiSecurity" class="form-select"><option value="WPA">WPA / WPA2 / WPA3</option><option value="WEP">WEP</option><option value="nopass">No password</option></select></label><label class="fs-span">Password<input id="fsWifiPass" class="form-input" type="password"></label></div>',
  '<div class="fs-special" data-fs-q="contact"><label>Name<input id="fsContactName" class="form-input"></label><label>Phone<input id="fsContactPhone" class="form-input"></label><label>Email<input id="fsContactEmail" class="form-input"></label><label>Website<input id="fsContactUrl" class="form-input" placeholder="https://"></label></div>',
  '<div class="fs-special" data-fs-q="email"><label>To<input id="fsEmailTo" class="form-input"></label><label>Subject<input id="fsEmailSubject" class="form-input"></label><label class="fs-span">Body<textarea id="fsEmailBody" class="form-textarea" rows="3"></textarea></label></div>',
  '<div class="fs-special" data-fs-q="phone"><label class="fs-span">Phone<input id="fsPhone" class="form-input" placeholder="+91..."></label></div>',
  '<div class="fs-special" data-fs-q="sms"><label class="fs-span">Phone<input id="fsSmsPhone" class="form-input"></label><label class="fs-span">Message<textarea id="fsSmsText" class="form-textarea" rows="3"></textarea></label></div>',
  '<div class="fs-special" data-fs-q="location"><label>Latitude<input id="fsLat" class="form-input" inputmode="decimal"></label><label>Longitude<input id="fsLon" class="form-input" inputmode="decimal"></label></div>',
 '</div>',
 '<div class="card fs-card"><div class="code-kicker">DESIGN</div><h2>Shape it</h2><div class="fs-design-grid"><label>Dots<select id="fsQrDots" class="form-select"><option value="square">Square</option><option value="rounded" selected>Rounded</option><option value="dots">Dots</option><option value="classy">Classy</option><option value="classy-rounded">Classy rounded</option><option value="extra-rounded">Extra rounded</option></select></label><label>Corner style<select id="fsQrCorner" class="form-select"><option value="square">Square</option><option value="rounded">Rounded</option><option value="dot">Dot</option><option value="extra-rounded" selected>Extra rounded</option></select></label><label>Corner dot<select id="fsQrCornerDot" class="form-select"><option value="square">Square</option><option value="dot" selected>Dot</option><option value="rounded">Rounded</option></select></label><label>Error correction<select id="fsQrEcc" class="form-select"><option>L</option><option>M</option><option>Q</option><option selected>H</option></select></label></div>',
  '<div class="fs-colors"><label><input id="fsQrFg" type="color" value="#172B4D"><span>Foreground</span></label><label><input id="fsQrFg2" type="color" value="#D9571F"><span>Accent</span></label><label><input id="fsQrBg" type="color" value="#FFFFFF"><span>Background</span></label></div>',
  '<div class="fs-checks"><label class="fs-check"><input id="fsQrGradient" type="checkbox"> Gradient dots</label><label class="fs-check"><input id="fsQrTransparent" type="checkbox"> Transparent background</label></div>',
  '<label class="fs-logo">Optional center logo <input id="fsQrLogo" type="file" accept="image/*"></label></div>',
'</div>',
'<div class="card fs-qr-result"><div class="fs-qr-copy"><div class="code-kicker">PREVIEW</div><h2>Static QR</h2><p id="fsQrStatus" class="fs-status">Enter content to generate.</p><code id="fsQrDataPreview"></code><div class="fs-actions"><button id="fsQrPng" class="btn btn-primary" type="button">Download PNG</button><button id="fsQrSvg" class="btn btn-secondary" type="button">Download SVG</button></div></div><div id="fsQrPreview" class="fs-qr-preview"><div class="fs-empty"><b>▦</b>Your QR will appear here.</div></div></div>',
'</div>',
/* Transfer panel */
'<div class="fs-panel fs-transfer-panel" hidden>',
 '<div class="card fs-transfer-setup"><div class="fs-transfer-intro"><div class="code-kicker">PRIVATE LAN TRANSFER</div><h2>Computer ↔ Phone, without cloud</h2><p class="sub">Pick a direction, start a session, then scan the QR with your phone camera. Both devices must be on the same Wi-Fi.</p></div>',
  '<div class="fs-direction" role="radiogroup" aria-label="Transfer direction"><button type="button" class="fs-dir active" data-dir="send" role="radio" aria-checked="true"><b>↑ Send to phone</b><span>Share files from this computer</span></button><button type="button" class="fs-dir" data-dir="receive" role="radio" aria-checked="false"><b>↓ Receive from phone</b><span>Phone uploads into Downloads › Omni Transfers</span></button></div>',
  '<select id="fsTransferMode" hidden><option value="send">send</option><option value="receive">receive</option></select>',
  '<div id="fsSendBox"><div class="fs-drop" id="fsDrop"><input id="fsFiles" type="file" multiple hidden><strong>Drop files here</strong><span>or</span><button id="fsPick" class="btn btn-secondary" type="button">Select Files</button></div><div id="fsFileList" class="fs-file-list"></div></div>',
  '<div id="fsReceiveBox" class="fs-receive-note" hidden><b>↓</b><div><strong>Ready to receive</strong><span>Files sent from your phone are saved straight to <em>Downloads › Omni Transfers</em> on this computer and stay there after the session ends.</span></div></div>',
  '<div class="fs-transfer-actions"><button id="fsStart" class="btn btn-primary" type="button">Start sharing</button><button id="fsStop" class="btn btn-secondary" type="button" hidden>Stop session</button></div>',
 '</div>',
 '<div class="fs-transfer-grid"><div class="card fs-session fs-pair"><div class="code-kicker">PAIR DEVICE</div><h2>Scan with your phone</h2><div id="fsTransferQr" class="fs-transfer-qr"><div class="fs-empty"><b>⇄</b>Start a session to create the QR code.</div></div><div id="fsTransferPin" class="fs-pin"></div><div id="fsTransferUrl" class="fs-transfer-url"></div><button id="fsCopyUrl" class="btn btn-secondary" type="button" hidden>Copy link</button></div>',
  '<div class="card fs-session"><div class="fs-session-head"><div><div class="code-kicker">SESSION</div><h2 id="fsTransferState">Not started</h2></div><span id="fsCountdown" class="fs-countdown" hidden></span></div><div id="fsTransferStatus" class="fs-status">Nothing is shared yet.</div><div id="fsTransferFiles" class="fs-received-list"></div><button id="fsOpenInbox" class="btn btn-secondary fs-open-inbox" type="button" hidden>Open Omni Transfers folder</button><div class="fs-security-list"><span>✓ Random session link + PIN</span><span>✓ Expires after 15 minutes</span><span>✓ Same Wi-Fi only, no cloud</span><span>✓ Transfer server stops with the session</span></div></div></div>',
'</div>'
].join('');return p}

/* ---------- Wiring ---------- */
function install(){if($(ID))return;const nav=document.querySelector('.nav-bar'),container=document.querySelector('.container');if(!nav||!container)return;const b=document.createElement('button');b.type='button';b.className='nav-btn';b.dataset.tab=ID;b.innerHTML='<span class="studio-icon"><span class="studio-svg">⇄</span></span><span class="studio-label">File Sharing</span><small>QR • LAN</small>';nav.appendChild(b);const p=panel();container.appendChild(p);bind(b,p)}
function activate(on,b,p){if(on){document.querySelectorAll('.module-panel').forEach(x=>x.classList.toggle('active',x===p));document.querySelectorAll('.nav-bar .nav-btn').forEach(x=>x.classList.toggle('active',x===b));document.body.classList.add('studio-mode');document.body.dataset.activeStudio=ID;document.body.style.setProperty('--active-studio-accent',ACCENT);document.body.style.setProperty('--active-studio-accent-2',ACCENT2);document.body.style.setProperty('--active-studio-soft','rgba(15,118,110,.14)')}else{b.classList.remove('active');p.classList.remove('active')}}
function setDirection(p,dir){if(transferToken&&dir!==transferMode){setTransferStatus('Stop the current session before switching direction.','warn');return}transferMode=dir;$('fsTransferMode').value=dir;p.querySelectorAll('.fs-dir').forEach(x=>{const on=x.dataset.dir===dir;x.classList.toggle('active',on);x.setAttribute('aria-checked',on)});$('fsSendBox').hidden=dir!=='send';$('fsReceiveBox').hidden=dir!=='receive';$('fsStart').textContent=dir==='send'?'Start sharing':'Start receiving';if(!transferToken)setTransferStatus(dir==='send'?'Select files, then start sharing.':'Start receiving, then scan the QR with your phone.','')}
function bind(b,p){
 b.onclick=e=>{e.preventDefault();e.stopPropagation();activate(true,b,p);p.scrollIntoView({behavior:'smooth',block:'start'})};
 document.addEventListener('click',e=>{const n=e.target.closest?.('.nav-bar .nav-btn');if(n&&n!==b)activate(false,b,p)});
 const switchMode=mode=>{p.querySelector('.fs-qr-panel').hidden=mode!=='qr';p.querySelector('.fs-transfer-panel').hidden=mode!=='transfer';p.querySelectorAll('.fs-share-option').forEach(y=>{const on=y.dataset.openMode===mode;y.classList.toggle('selected',on);y.setAttribute('aria-selected',on)})};
 p.querySelectorAll('.fs-share-option').forEach(x=>x.onclick=()=>switchMode(x.dataset.openMode));
 p.querySelector('#fsQrType').onchange=showQrFields;
 p.querySelector('.fs-qr-panel').querySelectorAll('input,select,textarea').forEach(x=>x.addEventListener('input',()=>{if(x.id!=='fsQrLogo')renderQr()}));
 p.querySelector('#fsQrLogo').onchange=async e=>{const f=e.target.files?.[0];logoData=f?await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)}):'';renderQr()};
 p.querySelector('#fsQrPng').onclick=()=>downloadQr('png');p.querySelector('#fsQrSvg').onclick=()=>downloadQr('svg');
 p.querySelectorAll('.fs-dir').forEach(x=>x.onclick=()=>setDirection(p,x.dataset.dir));
 p.querySelector('#fsPick').onclick=()=>p.querySelector('#fsFiles').click();
 p.querySelector('#fsFiles').onchange=e=>{addFiles(e.target.files);e.target.value=''};
 const d=p.querySelector('#fsDrop');['dragenter','dragover'].forEach(n=>d.addEventListener(n,e=>{e.preventDefault();d.classList.add('dragover')}));['dragleave','drop'].forEach(n=>d.addEventListener(n,e=>{e.preventDefault();d.classList.remove('dragover')}));d.ondrop=e=>addFiles(e.dataTransfer.files);
 p.querySelector('#fsStart').onclick=startTransfer;p.querySelector('#fsStop').onclick=()=>stopTransfer();
 p.querySelector('#fsCopyUrl').onclick=async()=>{const u=$('fsTransferUrl').textContent;try{await navigator.clipboard.writeText(u);flash($('fsCopyUrl'),'Copied ✓')}catch(e){setTransferStatus('Copy failed — select the link text instead.','warn')}};
 p.querySelector('#fsOpenInbox').onclick=()=>reveal('');
 p.querySelector('#fsTransferFiles').addEventListener('click',e=>{const x=e.target.closest('[data-reveal]');if(x)reveal(x.dataset.reveal)});
 setDirection(p,'send');showQrFields();
}
function flash(btn,text){const t=btn.textContent;btn.textContent=text;setTimeout(()=>btn.textContent=t,1400)}
function setTransferStatus(t,k){const e=$('fsTransferStatus');if(e){e.textContent=t;e.className='fs-status '+(k||'')}}
function renderPicked(){const e=$('fsFileList');e.innerHTML=transferFiles.map((f,i)=>'<div><span class="fs-ext">'+esc(extOf(f.name))+'</span><span class="fs-fn">'+esc(f.name)+'</span><small>'+fmt(f.size)+'</small><button type="button" data-r="'+i+'" aria-label="Remove '+esc(f.name)+'">×</button></div>').join('');e.querySelectorAll('[data-r]').forEach(x=>x.onclick=()=>{transferFiles.splice(+x.dataset.r,1);renderPicked()})}
function addFiles(fs){for(const f of fs||[]){if(f.size>8*1024**3){setTransferStatus(f.name+' is too large for the local transfer limit.','warn');continue}transferFiles.push(f)}renderPicked()}
async function uploadSelected(){const ids=[];let n=0;for(const f of transferFiles){n++;setTransferStatus('Preparing '+f.name+' ('+n+'/'+transferFiles.length+')…','working');const t=await localToken();const r=await fetch(localBase()+'/api/upload',{method:'POST',headers:{'X-Omni-Token':t,'X-Filename':encodeURIComponent(f.name),'Content-Type':f.type||'application/octet-stream'},body:f});const j=await r.json();if(!r.ok)throw new Error(j.error||'Upload failed');ids.push(j.file_id)}return ids}
function sessionUi(live){$('fsStart').hidden=live;$('fsStop').hidden=!live;$('fsCopyUrl').hidden=!live;$('fsCountdown').hidden=!live;$('fsOpenInbox').hidden=!(live&&transferMode==='receive');document.querySelectorAll('#'+ID+' .fs-dir').forEach(x=>x.disabled=live);const pk=$('fsPick');if(pk)pk.disabled=live}
function tickCountdown(){const el=$('fsCountdown');if(!el||!transferExpires)return;const s=Math.max(0,Math.round(transferExpires-Date.now()/1000));el.textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0')+' left';if(!s)stopTransfer('Session expired. Start a new one to transfer more files.')}
async function startTransfer(){if(transferToken)await stopTransfer();transferMode=val('fsTransferMode')||transferMode;const startBtn=$('fsStart');startBtn.disabled=true;try{if(transferMode==='send'&&!transferFiles.length)throw new Error('Select at least one file to send.');const ids=transferMode==='send'?await uploadSelected():[];setTransferStatus('Starting the Wi-Fi transfer server…','working');const j=await localFetch('/api/transfer/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:transferMode,file_ids:ids,names:transferMode==='send'?transferFiles.map(f=>f.name):[],ttl:900})});transferToken=j.token;transferExpires=j.expires||(Date.now()/1000+j.ttl);lastFileCount=0;sessionUi(true);$('fsTransferState').textContent='Waiting for phone';$('fsTransferPin').textContent=j.pin;$('fsTransferUrl').textContent=j.url;const m=$('fsTransferQr');m.innerHTML=await plainQrSvg(j.url,'#0B3D3A');if(j.warning)setTransferStatus(j.warning+' The phone will not be able to reach it.','warn');else setTransferStatus(transferMode==='send'?'Scan the QR with your phone camera, then tap Save on each file.':'Scan the QR with your phone camera, then choose files to send.','ok');clearInterval(countdownTimer);countdownTimer=setInterval(tickCountdown,1000);tickCountdown();renderSessionFiles([]);pollTransfer()}catch(e){setTransferStatus(e.message,'warn')}finally{startBtn.disabled=false}}
function renderSessionFiles(files){const e=$('fsTransferFiles');if(transferMode==='send'){e.innerHTML=files.map(f=>'<div class="fs-received"><span class="fs-ext">'+esc(extOf(f.name))+'</span><div><b>'+esc(f.name)+'</b><small>'+fmt(f.size)+' · shared</small></div></div>').join('');return}e.innerHTML=files.slice().reverse().map(f=>'<div class="fs-received"><span class="fs-ext">'+esc(extOf(f.name))+'</span><div><b>'+esc(f.name)+'</b><small>'+fmt(f.size)+' · saved to Omni Transfers</small></div><button type="button" class="btn btn-secondary" data-reveal="'+esc(f.id)+'">Show</button></div>').join('')||'<div class="fs-empty-inline">Waiting for files from your phone…</div>'}
async function reveal(fid){try{await localFetch('/api/transfer/reveal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:transferToken,id:fid})})}catch(e){setTransferStatus(e.message,'warn')}}
async function pollTransfer(){clearTimeout(transferTimer);if(!transferToken)return;try{const j=await localFetch('/api/transfer/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:transferToken})});const files=j.files||[];$('fsTransferState').textContent=j.active?'Phone connected':(j.connected?'Phone was connected':'Waiting for phone');renderSessionFiles(files);if(transferMode==='receive'&&files.length>lastFileCount){setTransferStatus(files.length+(files.length>1?' files':' file')+' received. Saved in Downloads › Omni Transfers.','ok')}else if(j.active&&transferMode==='send'&&!lastFileCount){setTransferStatus('Phone connected — tap Save on the phone to download.','ok')}lastFileCount=files.length}catch(e){if(e.status===404){stopTransfer('Session ended. Start a new one to transfer more files.');return}setTransferStatus(e.message,'warn')}if(transferToken)transferTimer=setTimeout(pollTransfer,1800)}
async function stopTransfer(message){clearTimeout(transferTimer);transferTimer=null;clearInterval(countdownTimer);countdownTimer=null;const tok=transferToken;transferToken='';transferExpires=0;if(tok){try{await localFetch('/api/transfer/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:tok})})}catch(e){}}sessionUi(false);$('fsTransferQr').innerHTML='<div class="fs-empty"><b>⇄</b>Start a session to create the QR code.</div>';$('fsTransferPin').textContent='';$('fsTransferUrl').textContent='';$('fsTransferState').textContent='Not started';if(transferMode==='send'){$('fsTransferFiles').innerHTML=''}setTransferStatus(typeof message==='string'?message:(transferMode==='receive'&&lastFileCount?'Session stopped. Received files are kept in Downloads › Omni Transfers.':'Session stopped.'),'')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
window.addEventListener('beforeunload',()=>{if(transferToken)navigator.sendBeacon?.(localBase()+'/api/transfer/stop',new Blob([JSON.stringify({token:transferToken})],{type:'application/json'}))});
})();
