/* Omni Suite — site-wide assistant
 * Product RAG + local small LLM. Uses curated knowledge-base files and optionally
 * the Private RAG IndexedDB corpus when available.
 */
(()=>{"use strict";
const CDN="https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2";
const EMBED="Xenova/all-MiniLM-L6-v2", LLM="Xenova/Qwen1.5-0.5B-Chat";
let embedder=null,generator=null,docs=[],vectors=[],busy=false;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function styles(){if(document.getElementById("omni-assistant-css"))return;const s=document.createElement("style");s.id="omni-assistant-css";s.textContent=`
#omniAssistantButton{position:fixed;right:22px;bottom:22px;z-index:90;border:0;border-radius:18px;padding:12px 16px;background:linear-gradient(135deg,#6c5cff,#ff4f9a);color:#fff;font-weight:850;box-shadow:0 18px 38px -14px rgba(80,60,190,.55);cursor:pointer;display:flex;gap:9px;align-items:center}
#omniAssistantButton:hover{transform:translateY(-3px)}#omniAssistantPanel{position:fixed;right:22px;bottom:78px;z-index:91;width:min(430px,calc(100vw - 28px));height:min(650px,calc(100vh - 110px));display:none;flex-direction:column;overflow:hidden;border:1px solid rgba(108,92,255,.18);border-radius:24px;background:rgba(255,255,255,.97);box-shadow:0 30px 80px -24px rgba(45,36,110,.45);backdrop-filter:blur(18px)}
#omniAssistantPanel.open{display:flex;animation:omniAsIn .3s ease}.omni-as-head{padding:17px 18px;border-bottom:1px solid #eceaf5;background:linear-gradient(135deg,#f8f6ff,#fff)}
.omni-as-title{display:flex;align-items:center;justify-content:space-between;gap:12px}.omni-as-title strong{font-size:1rem}.omni-as-badge{font-size:.65rem;font-weight:900;padding:5px 8px;border-radius:999px;background:#e7fbf4;color:#087f5b}
.omni-as-sub{font-size:.75rem;color:#73788d;margin-top:5px;line-height:1.45}.omni-as-chat{flex:1;overflow:auto;padding:14px;background:#fafbfe}
.omni-as-msg{max-width:88%;padding:10px 12px;border-radius:15px;margin:0 0 10px;white-space:pre-wrap;line-height:1.48;font-size:.82rem}
.omni-as-msg.bot{background:#fff;border:1px solid #e6e8ef;color:#29304a}.omni-as-msg.user{margin-left:auto;background:#6c5cff;color:#fff}
.omni-as-source{margin-top:8px;padding:7px 9px;border-radius:10px;background:#f4f2ff;color:#6259a0;font-size:.68rem}
.omni-as-form{display:flex;gap:8px;padding:11px;border-top:1px solid #eceef4;background:#fff}.omni-as-form textarea{flex:1;min-height:42px;max-height:110px;resize:none;border:1px solid #dfe3ec;border-radius:13px;padding:10px;font:inherit;font-size:.8rem}.omni-as-send{border:0;border-radius:13px;padding:0 13px;background:#1c1b3a;color:#fff;font-weight:800;cursor:pointer}.omni-as-clear{position:absolute;right:52px;top:17px;border:0;background:transparent;color:#85899b;cursor:pointer}
@keyframes omniAsIn{from{opacity:0;transform:translateY(12px) scale(.98)}to{opacity:1;transform:none}}
@media(max-width:600px){#omniAssistantButton{right:14px;bottom:14px}#omniAssistantPanel{right:14px;bottom:70px;width:calc(100vw - 28px);height:calc(100vh - 92px);border-radius:20px}}
`;document.head.appendChild(s)}
function ui(){if(document.getElementById("omniAssistantPanel"))return;const b=document.createElement("button");b.id="omniAssistantButton";b.innerHTML="✦ <span>Ask Omni</span>";b.onclick=()=>toggle();document.body.appendChild(b);const p=document.createElement("section");p.id="omniAssistantPanel";p.setAttribute("aria-label","Omni Assistant");p.innerHTML=`<div class="omni-as-head"><div class="omni-as-title"><strong>Omni Assistant</strong><span class="omni-as-badge" id="omniAsStatus">LOCAL-FIRST</span></div><button class="omni-as-clear" id="omniAsClear" title="Clear chat">×</button><div class="omni-as-sub">Ask how Omni Suite works, which Studio to use, supported workflows, privacy, or troubleshooting.</div></div><div class="omni-as-chat" id="omniAsChat"><div class="omni-as-msg bot">Hi! I’m Omni Assistant. Ask me anything about the tools and workflows on this website.</div></div><div class="omni-as-form"><textarea id="omniAsInput" placeholder="e.g. How do I convert PDF to PowerPoint?" aria-label="Ask Omni"></textarea><button class="omni-as-send" id="omniAsSend">Ask</button></div>`;document.body.appendChild(p);document.getElementById("omniAsSend").onclick=ask;document.getElementById("omniAsInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}});document.getElementById("omniAsClear").onclick=()=>document.getElementById("omniAsChat").innerHTML='<div class="omni-as-msg bot">Chat cleared. What would you like to know about Omni Suite?</div>'}
function toggle(){document.getElementById("omniAssistantPanel").classList.toggle("open")}
async function transformers(){if(window.__omniTransformers)return window.__omniTransformers;return window.__omniTransformers=await import(CDN)}
function split(t){t=t.replace(/\r/g,"").trim();const out=[];for(let i=0;i<t.length;i+=760){const c=t.slice(i,i+900).trim();if(c)out.push(c);if(i+900>=t.length)break}return out}
function lex(q,t){const a=new Set((q.toLowerCase().match(/[a-z0-9_-]{2,}/g)||[])),b=t.toLowerCase().match(/[a-z0-9_-]{2,}/g)||[];let n=0;for(const x of b)if(a.has(x))n++;return n/Math.sqrt(Math.max(1,a.size*b.length))}
function cos(a,b){let d=0,na=0,nb=0;for(let i=0;i<a.length;i++){d+=a[i]*b[i];na+=a[i]*a[i];nb+=b[i]*b[i]}return d/(Math.sqrt(na*nb)||1)}
async function emb(t){if(!embedder){document.getElementById("omniAsStatus").textContent="LOADING AI";const m=await transformers();embedder=await m.pipeline("feature-extraction",EMBED,{dtype:"q8"})}const o=await embedder(t,{pooling:"mean",normalize:true});return Array.from(o.data)}
async function loadKnowledge(){if(docs.length)return;const base=location.href.replace(/[^/]+$/,"");try{const mr=await fetch(base+"knowledge-base/manifest.json",{cache:"no-store"});if(mr.ok){const j=await mr.json();for(const f of (Array.isArray(j)?j:j.files||[])){const r=await fetch(base+"knowledge-base/"+(f.path||f),{cache:"no-store"});if(r.ok){const text=await r.text();for(const c of split(text))docs.push({source:f.title||f.path||f,text:c})}}}}catch(e){}try{const r=indexedDB.open("omni-private-rag-v1",1);r.onsuccess=()=>{const db=r.result;if(!db.objectStoreNames.contains("chunks"))return;const q=db.transaction("chunks","readonly").objectStore("chunks").getAll();q.onsuccess=()=>{for(const x of q.result||[])docs.push({source:"Private RAG: "+x.source,text:x.text,vector:x.vector})}}}catch(e){}}
async function retrieve(q){await loadKnowledge();if(!docs.length)return[];const qv=await emb(q);const scored=[];for(const d of docs){const v=d.vector?cos(qv,d.vector):0;scored.push({...d,score:.78*v+.22*lex(q,d.text)})}const missing=scored.filter(x=>!x.vector);if(missing.length){for(const d of missing){d.vector=await emb(d.text)}}return scored.sort((a,b)=>b.score-a.score).slice(0,6)}
async function generate(q,r){const m=await transformers();if(!generator){document.getElementById("omniAsStatus").textContent="LOADING LLM";generator=await m.pipeline("text-generation",LLM,{dtype:"q4",device:navigator.gpu?"webgpu":"wasm"})}const context=r.map((x,i)=>"[Source "+(i+1)+": "+x.source+"]\n"+x.text).join("\n\n");const prompt="You are Omni Assistant for Omni Suite. Answer only from the supplied sources. Be concise and practical. If the sources do not support the answer, say that you do not have enough verified information. Do not invent tools or capabilities.\n\nSOURCES:\n"+context+"\n\nUSER QUESTION: "+q+"\nANSWER:";const o=await generator(prompt,{max_new_tokens:220,temperature:.15,do_sample:false});const raw=Array.isArray(o)?o[0]?.generated_text||"":String(o);return raw.includes("ANSWER:")?raw.split("ANSWER:").pop().trim():raw.replace(prompt,"").trim()}
function add(text,kind){const c=document.createElement("div");c.className="omni-as-msg "+kind;c.textContent=text;document.getElementById("omniAsChat").appendChild(c);c.scrollIntoView({block:"end"});return c}
async function ask(){if(busy)return;const input=document.getElementById("omniAsInput"),q=input.value.trim();if(!q)return;input.value="";add(q,"user");const wait=add("Searching Omni Suite knowledge…","bot");busy=true;try{const r=await retrieve(q);if(!r.length){wait.textContent="I don’t have verified information for that yet. Try asking about a Studio, conversion, supported workflow, privacy, or troubleshooting."}else{let ans;try{ans=await generate(q,r);document.getElementById("omniAsStatus").textContent=navigator.gpu?"LOCAL · WEBGPU":"LOCAL · WASM"}catch(e){ans=r[0].text;document.getElementById("omniAsStatus").textContent="RETRIEVAL FALLBACK"}wait.textContent=ans;const src=document.createElement("div");src.className="omni-as-source";src.textContent="Sources: "+r.slice(0,3).map(x=>x.source).join(" · ");wait.appendChild(src)}}catch(e){wait.textContent="I couldn’t complete the local retrieval right now. Please try again; the assistant does not send your question to a remote AI API."}finally{busy=false}}
function start(){styles();ui()}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();